#!/bin/bash	
# Uninstall script 
# Stop deskpi.service.
systemctl stop deskpi.service
systemctl disable deskpi.service

# Define file locations
installation_dir="/storage"
# Greetings and information for user.
log_action_msg "Welcome to Use DeskPi-Team's Product"
log_action_msg "Please select what distribution you have: "
log_action_msg "1 - Raspbian"
log_action_msg "2 - Manjaro"
log_action_msg "3 - Ubuntu Mate"
log_action_msg "4 - Kali"
log_action_msg "5 - Libreelec"
log_action_msg "6 - Cancel Uninstallation Process"
log_action_msg "Just input the number and press enter."
read -p "Your choice:" os_type
case $os_type in
	1) 
	   log_action_msg "Uninstalling DeskPi Utilities"
	   bash $installation_dir/uninstall.sh
	   sh -c "rm -f /etc/deskpi.conf" 
	   ;;
	2) 
	   log_action_msg "Uninstalling DeskPi Utilities"
	   bash $installation_dir/uninstall-manjaro.sh
	   sh -c "rm -f /etc/deskpi.conf" 
	   ;;
	3) 
	   log_action_msg "Uninstalling DeskPi Utilities"
	   bash $installation_dir/uninstall-ubuntu-mate.sh
	   sh -c "rm -f /etc/deskpi.conf" 
	   ;;
	4) 
	   log_action_msg "Uninstalling DeskPi Utilities"
	   bash $installation_dir/uninstall-kali.sh
	   sh -c "rm -f /etc/deskpi.conf" 
	   ;;
	5) 
	   log_action_msg "Uninstalling Deskpi Utilities"
	   bash $installation_dir/uninstall-libreelec.sh
	   sh -c "rm -f /storage/usr/bin/deskpi.conf"
	   ;;
	6) 
	   log_action_msg "Uninstallation Canceled"
	   ;;
	*) 
	   log_action_msg "Error selection please try again"
	   . /storage/usr/bin/Deskpi-uninstall
	   ;;
esac
